SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID  FROM Hr.DEPARTMENTS d WHERE DEPARTMENT_NAME = 'IT' OR  DEPARTMENT_Name = 'Finance') AND (SALARY < 6000 or SALARY > 12000)

SELECT DEPARTMENT_ID  FROM Hr.DEPARTMENTS d WHERE DEPARTMENT_NAME = 'IT' OR  DEPARTMENT_Name = 'Finance'

SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID  FROM Hr.DEPARTMENTS d WHERE DEPARTMENT_NAME = 'IT' OR  DEPARTMENT_Name = 'Finance') AND SALARY > 6000 and SALARY < 12000

SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID  FROM Hr.DEPARTMENTS d WHERE DEPARTMENT_NAME = 'IT' OR  DEPARTMENT_Name = 'Finance') AND SALARY < 6000 or SALARY > 12000